serverHost: 120.78.128.247
server:
  port: 8080
  session:
    timeout: 7200
  tomcat:
    uri-encoding: UTF-8
  jsp-servlet:
    init-parameters:
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  data:
    mongodb:
      uri: mongodb://tvis:sztvis@${serverHost}:27017/buscloud
  datasource:
    url: jdbc:mysql://${serverHost}:3306/buscloud?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: sztvis@com.6789
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
mybatis:
  type-aliases-package: com.sztvis.buscloud.model.domain
  mapper-locations: classpath:/mybatis/*.xml
mapper:
  mappers: com.sztvis.buscloud.core.BusCloudMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count
jedis:
  pool:
    host: ${serverHost}
    port: 6379
    config:
      maxTotal: 200
      maxIdle: 200
      maxWaitMillis : 100000
ytx:
  account:
upload:
  dir: classpath:/uploads/
logging:
  level:
    com:
      sztvis:
        buscloud:
          mapper: debug
shiro:
    configLocation: classpath:/ehcache-shiro.xml
