serverHost: 120.78.128.247
server:
  port: 8080
  session:
    timeout: 20
  tomcat:
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  data:
    mongodb:
      uri: mongodb://${serverHost}:27017/buscloud
  datasource:
    url: jdbc:mysql://${serverHost}:3306/buscloud?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: sztvis@com.6789
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
  redis:
    database: 0
    #服务地址
    host: ${serverHost}
    port: 6379
    password:
    pool:
      max-active: 8 #连接池最大连接数，使用负值表示没有限制
      max-wait: -1 #连接池最大阻塞等待时间，使用负值表示没有限制
      max-idel: 8 #最大空闲连接
      min-idel: 0 #最小空闲连接
    timeout: 0 #连接超时时间（毫秒）
mybatis:
  type-aliases-package: com.sztvis.buscloud.model.domain
  mapper-locations: classpath:/mybatis/*.xml
mapper:
  mappers: com.sztvis.buscloud.core.BusCloudMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count

